plugins:
  - jekyll-redirect-from
  - jekyll-remote-theme

remote_theme:         andrewgjohnson/open-source-documentation-jekyll-theme
title:                AgjGd
name:                 AgjGd
description:          AgjGd extends the functionality of PHP’s GD library. It is a single class, \AndrewGJohnson\AgjGd, with functionality exposed via public static methods
author:               Andrew G. Johnson
author_email:         andrew@andrewgjohnson.com
email:                agjgd.org@gmail.com
url:                  https://AgjGd.org
includes_dir:         .
favicon:              https://github.githubassets.com/favicon.ico
footer_text:          AgjGd.org
footer_url:           /
copyright_year_start: 2013
syntax_highlighting:  true
cover_image:          mountains
custom_head:          <script>if (location.pathname == "/documentation" || location.pathname.indexOf("/documentation/") === 0) window.location.href = "/";</script>
social_links:
  - platform:         twitter
    url:              https://twitter.com/agjgdphp
    label:            AgjGd on Twitter
  - platform:         github
    url:              https://github.com/andrewgjohnson/AgjGd
    label:            AgjGd on GitHub
  - platform:         packagist
    url:              https://packagist.org/packages/andrewgjohnson/agjgd
    label:            AgjGd on Packagist
  - platform:         patreon
    url:              https://www.patreon.com/agjopensource
    label:            AgjGd on Patreon
  - platform:         x
    url:              https://x.com/agjgdphp
    label:            AgjGd on 𝕏
exclude:              [
                       .github,
                       .github/*.md,
                       .github/*.yml,
                       .github/CODEOWNERS,
                       CHANGELOG.md,
                       CNAME,
                       composer.json,
                       composer.lock,
                       data,
                       data/*.json,
                       documentation/README.md,
                       examples/README.md,
                       examples/*.ttf,
                       examples/*.txt,
                       examples/*/*.php,
                       LICENSE,
                       phpcs.xml.dist,
                       phpstan,
                       phpstan.neon.dist,
                       phpstan-php80.neon.dist,
                       phpunit.xml.dist,
                       README.md,
                       source,
                       tests,
                       vendor,
                       vendor/*.md
                      ]
